services:
    frontend:
        container_name: colocaton-frontend
        build:
            context: ./front
            dockerfile: Dockerfile
            args:
            - API_BACKEND_URL=${API_BACKEND_URL}
        environment:
        - VITE_API_URL=${API_BACKEND_URL}
        ports:
            - ${CLIENT_PORT}:5173
        networks:
        - colocaton-network
        depends_on:
        - backend
        restart: unless-stopped

    backend:
        container_name: colocaton-backend
        build:
            context: ./back
            dockerfile: Dockerfile
        environment:
        - NODE_ENV=${NODE_ENV}
        - FRONTEND_URL=${FRONTEND_URL}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
        ports:
            - ${SERVER_PORT}:5000
        networks:
        - colocaton-network
        volumes:
        - ./back/uploads:/usr/app/uploads
        depends_on:
            db:
                condition: service_healthy
        restart: unless-stopped


    db:
        image: postgres:latest
        container_name: colocaton-postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d colocaton"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
        - colocaton-pgdata:/var/lib/postgresql/18/main
        networks:
        - colocaton-network
        restart: unless-stopped

networks:
    colocaton-network:
        driver: bridge
volumes:
    colocaton-pgdata:
        driver: local
