services:
    frontend:
        image: ghcr.io/gaspachoo/colocaton-front:latest
        container_name: colocaton-frontend
        environment:
          - VITE_API_URL=${API_BACKEND_URL}
        labels:
          - "com.centurylinklabs.watchtower.enable=true"
        ports:
            - ${CLIENT_PORT}:5173
        networks:
        - colocaton-network
        depends_on:
        - backend
        restart: unless-stopped

    backend:
        image: ghcr.io/gaspachoo/colocaton-back:latest
        container_name: colocaton-backend
        environment:
        - NODE_ENV=${NODE_ENV}
        - FRONTEND_URL=${FRONTEND_URL}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        ports:
            - ${SERVER_PORT}:5000
        networks:
        - colocaton-network
        volumes:
        - ./back/uploads:/usr/app/uploads
        depends_on:
            db:
                condition: service_healthy
        restart: unless-stopped

    db:
        image: postgres:latest
        container_name: colocaton-postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U user -d colocaton"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
        - colocaton-pgdata:/var/lib/postgresql/18/main
        networks:
        - colocaton-network
        restart: unless-stopped

    watchtower:
      image: containrrr/watchtower:latest
      container_name: watchtower
      restart: unless-stopped
      # Intervalle = 300 s (5 min) ; --cleanup supprime l’ancienne image après maj
      # --label-enable : ne touche qu’aux conteneurs marqués ci-dessus
      command: >
        --interval 3600
        --cleanup
        --label-enable
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /home/admin/.docker/config.json:/config.json:ro
      environment:
        - TZ=Europe/Paris
        - REGISTRY_AUTH_FILE=/config.json


networks:
    colocaton-network:
        driver: bridge
volumes:
    colocaton-pgdata:
        driver: local
